[alembic]
# path to migration scripts
directory = migrations

# sqlalchemy.url = driver url
dburi = postgresql+asyncpg://user:password@localhost/dbname

# logging
log_file = alembic.log

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console,fileHandler

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_fileHandler]
class = handlers.RotatingFileHandler
args = ('alembic.log', 'a', 10485760, 3)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(levelname)s] %(name)s: %(message)s